In this notebook, we're going to cover some of the most fundamental concepts of tensors using tensoflow, more specifically, we're going to cover. 
- Introdution to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors & Numpy
- Using @tf.function (a way to speed up your regular Python functions)
- Using GPUs with TensorFlow or TPUs
- Exercices to try for yourself

## Introduction to Tensors

In [1]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.10.0


In [2]:
tf.sysconfig.get_build_info()

OrderedDict([('cpu_compiler',
              'C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe'),
             ('cuda_compute_capabilities',
              ['sm_35', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'compute_80']),
             ('cuda_version', '64_112'),
             ('cudart_dll_name', 'cudart64_112.dll'),
             ('cudnn_dll_name', 'cudnn64_8.dll'),
             ('cudnn_version', '64_8'),
             ('is_cuda_build', True),
             ('is_rocm_build', False),
             ('is_tensorrt_build', False),
             ('msvcp_dll_names', 'msvcp140.dll,msvcp140_1.dll'),
             ('nvcuda_dll_name', 'nvcuda.dll')])

In [3]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [7]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [8]:

# check the dimension of our vector
vector.ndim

1

In [9]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 10], [7, 7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7,  7]])>

In [10]:
matrix.ndim

2

In [13]:
another_matrix = tf.constant([[10., 10.], [7., 7.], [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter7
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 10.],
       [ 7.,  7.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
# what's the number dimensions of another_matrix?
another_matrix.ndim

2

In [16]:
# let's create a tensor
tensor = tf.constant([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[13,14,15], [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [17]:
tensor.ndim

3

What we've created so far
- scalar: a single number
- vector: a number with direction (e.g wind speed and direction)
- matrix: a 2 dimensional array of numbers
- tensor: an n-dimensional array of numbers (when n can be any number,a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

# Creating tensors with tf.Variable

In [18]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [19]:
# create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [20]:
# let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:
# How about we try .assign()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [22]:
# let try change out unchangeable tensor
unchangeable_tensor[0] =7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [23]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

> **Note:** Rarely in practice will you need to decide whether to use _tf.constant_ or _tf.Variable_ to create tensors, as TensorFlow does this for you, however, if in doubt, use _tf.constant_ and change it later if needed.

# Create Random Tensors

In [30]:
# create random tensors with tensorflow
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibilyt
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibilyt
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [36]:
# Shuffle a tensor (valuable for when you want your data so the inherent)
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [58]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

**Exercise:** Read through TensorFlow documentation on random seed generation and pratice writing 5 random tensors and shuffle them.

It looks like if we want out suffled tensors to be in the same order, we've got to use **global** level random seed as well as the operation level random seed:

>  **Rule:** if both the global and the operation seed are set: Both seeds are used in conjunction to determite

In [61]:
# create a tensor of all ones
tf.ones([3, 2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [62]:
# create a tensor of all zeros
tf.zeros([3, 2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [63]:
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU computing

In [64]:
# you cal also turn numpy array into tensors
import numpy as np

In [73]:
# x = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

numpy_a = np.arange(0, 18, dtype=np.int32) # create a numpy array between 1 and 10 type int32
numpy_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [74]:
a = tf.constant(numpy_a)
a

<tf.Tensor: shape=(18,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])>

In [80]:
# shape=(3, 2, 3)
# [ [[0,1,2], [3,4,5]], [[6,7,8], [9,10,11]], [[12,13,14], [15,16,17]] ]

a = tf.constant(numpy_a, shape=(3, 2, 3))
b = tf.constant([ [[0,1,2], [3,4,5]], [[6,7,8], [9,10,11]], [[12,13,14], [15,16,17]] ])
a == b

<tf.Tensor: shape=(3, 2, 3), dtype=bool, numpy=
array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])>

# Getting more information from Tensors

- Shape: The length (number of elements) of each of the dimensions of a tensor
- Rank: The number of tensor dimensions. A scalar has rank 0, a vector has 1, a matrix has 2, a tensor has rank n
- Axis or dimension: A particular diemension of a tensor
- Size: Total number of items

In [85]:
# create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [88]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [90]:
# Get various attributes of out tensor
print('Datatype of every element: ', rank_4_tensor.dtype)
print('Number of dimensions (rank): ', rank_4_tensor.ndim)
print('Shape of tensor: ', rank_4_tensor.shape)
print('Elements along the 0 axis: ', rank_4_tensor.shape[0])
print('Elements along the last axis: ', rank_4_tensor.shape[-1])
print('Total number of elements in out tensor: ', tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in out tensor:  120


# Indexed tensors
Tensors can be indexed  just like Python lists

In [91]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [93]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [94]:
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [95]:
# create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant([[10, 7], [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [96]:
# add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [97]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand to final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [98]:

tf.expand_dims(rank_2_tensor, axis=0) # expand 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

# Manipulating tensors (tensor operations)
**Basic operations**
`+`, `-`, `*`, `/`, `%`

In [115]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10, tf.math.add(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>)

In [107]:
tensor * 10, tf.multiply(tensor, 10), tf.math.multiply(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>)

In [108]:
tensor - 10, tf.math.subtract(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]])>)

In [109]:
tensor / 10, tf.math.divide(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>)

In [110]:
tensor % 10, tf.math.mod(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 7],
        [3, 4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 7],
        [3, 4]])>)

 **Matrix multiplication**

 
 in machine learning matrix manipulation is one of the most common tensor operations.

 There are two rules our tensor (or metrics) need to fulfil if we're going to matrix multiply them:

 1. The inner dimensions must match
 2. The Resulting matrix has the shape of the inner dimensions

In [117]:
# matrix multiplication in tensorflow
tensor, tf.linalg.matmul(tensor, tensor)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>)

In [119]:
# matrix multiplication with Python operator
tensor, tensor * tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  49],
        [  9,  16]])>)

In [120]:
# matrix multiplication with Python operator '@'
tensor, tensor @ tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>)

In [127]:
tensor = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
tensor2 = tf.constant([[1,1], [2,2], [3, 3]])

tensor, tensor2, tf.matmul(tensor, tensor2)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 1],
        [2, 2],
        [3, 3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[14, 14],
        [32, 32],
        [50, 50]])>)

In [161]:
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

x = tf.constant([[1, 1],
                 [1, 1],
                 [1, 1]])

y @ tf.reshape(x, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15, 15, 15],
       [19, 19, 19],
       [23, 23, 23]])>

In [164]:
y, tf.reshape(y, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>)

In [168]:
y, tf.expand_dims(y, axis=0)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 <tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
 array([[[ 7,  8],
         [ 9, 10],
         [11, 12]]])>)

In [169]:
# can do the same with transpose
tf.transpose(x), tf.reshape(x, shape=(2, 3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 1, 1],
        [1, 1, 1]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 1, 1],
        [1, 1, 1]])>)

In [175]:
tf.transpose(tf.constant([[1,2,3], [4,5,6]])), tf.reshape(tf.constant([[1,2,3], [4,5,6]]), shape=(3, 2))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [3, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>)

**The dot product**

Matrix multiplication is also referred to as the dot product

you can perfom matrix multiplication using:
- `tf.matmul()`
- `tf.tensordot()`

In [176]:
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 1],
        [1, 1],
        [1, 1]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [177]:
# Perform the dot product on x and y (required x or y to be transposed)
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27, 30],
       [27, 30]])>

In [178]:
# perform matrix multiplication between x and y (transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15, 19, 23],
       [15, 19, 23],
       [15, 19, 23]])>

In [179]:
# perform matrix multiplication between x and y (reshaped)
tf.matmul(x, tf.reshape(y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 19, 21],
       [17, 19, 21],
       [17, 19, 21]])>

# Changing the datatype of a tensor